### ISSUE TITLE
Regarding the D4PG implementation

### ISSUE THREAD

**Issue by Tomohiro-Nagasaka** [fabiopardo/tonic#10]
First of all, thank you for providing an excellent RL library.

If I understand correctly, according to the D4PG paper, we should create multiple actors.  But it seems the implementation added from DDPG is only the distributional critic part?

reference: https://arxiv.org/pdf/1804.08617v1.pdf

![image](https://user-images.githubusercontent.com/78136723/106214085-0ac76700-6209-11eb-9bc5-cf3f5daa73ef.png)

**Comment by fabiopardo** [comment]
Hi! Thank you for your kind message. I'm glad you like the library.

As explained in the paper, all the agents in Tonic can directly be used with distributed training. For example when using the training script you can specify the number of workers to use (parallel and sequential) for any agent, including D4PG. I agree that the name D4PG might be confusing when not using distributed training, but D3PG is already associated with a few different agents in the literature.
