### ISSUE TITLE
No support/benchmark results for Atari games

### ISSUE THREAD

**Issue by mojivalipour** [fabiopardo/tonic#3]
It seems the current version doesn't support games like Breakout. The following code raise an error:

`python -m tonic.train --header "import tonic.torch" --agent "tonic.torch.agents.PPO()" --environment "tonic.environments.Gym('Breakout-v0')" --name PPO-X --seed 0`

AssertionError: `assert isinstance(env.action_space, gym.spaces.Box)`

Is that supposed to happen or the code is ready to use for other environments too other than the ones that you've provided the benchmarks. BTW, I think the benchmark idea for fast comparison is really cool. Thanks for sharing!

**Comment by fabiopardo** [comment]
Hey, really sorry for the late reply.
Indeed, Tonic currently supports continuous control only, but I am interested in extending it more. Feel free to contribute if you want! :)

**Comment by slerman12** [comment]
Any update on when/if pixel-based observations might be added? Great work! Thanks for publicizing this.

**Comment by fabiopardo** [comment]
Thanks! Not in the near future as I have to work on other projects but I would be very happy to accept pull requests for new features.
