### ISSUE TITLE
Win 10 compatibility issue with gym box (Comment Not an ISSUE)

### ISSUE THREAD

**Issue by mojivalipour** [fabiopardo/tonic#4]
Unfortunately for some reason, in Windows 10, there will be an assertion error for all the environments, even for the provided ones. It seems to me this is a Win 10 compatibility problem or a version issue with the Numpy or any other packages because simply commenting the following line in the gym\spaces\box.py can resolve the problem.

`assert np.isscalar(low) and np.isscalar(high)`

For example, without removing that line, the following code is not going to run. However, after commenting, it's working.

`python -m tonic.train --header "import tonic.torch" --agent "tonic.torch.agents.PPO()" --environment "tonic.environments.Gym('BipedalWalker-v2')" --name PPO-X --seed 0`

Hopefully, this helps others with the same problem.

**Comment by fabiopardo** [comment]
Hey! Sorry for the late reply.
Cool thanks for the feedback on WIndows. Unfortunately I have only tried Tonic on macOS and Ubuntu.
As you said, it seems to be a problem with Gym, have you opened an issue there?
